cabal-version:      3.0
name:               hons
version:            0.1.0.0
synopsis:           SCons-like build tool
homepage:           loonylinuxbox.mooo.com
license:            LGPL-3.0-or-later
license-file:       LICENSE
author:             Sergey Popov
maintainer:         loonycyborg@gmail.com
category:           Development

library
    exposed-modules:  Hons, Node, DepGraph, Taskmaster, Environment, Builder, CmdLine, Tool.CC
    build-depends:    base
                    , filepath >= 1.5.0.0
                    , os-string
                    , directory
                    , unix >= 2.8.6.0
                    , template-haskell
                    , algebraic-graphs >= 0.7
                    , containers
                    , unordered-containers
                    , text-short
                    , transformers
                    , hashable
                    , tagged
    hs-source-dirs:   src
    default-language: GHC2021

executable hons
    main-is:          Main.hs
    build-depends:
        base,
        hons,
        filepath >= 1.5.0.0,
        algebraic-graphs >= 0.7,
        transformers,
        text-short

    hs-source-dirs:   app
    default-language: GHC2021

test-suite hons-test
    default-language: GHC2021
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test
    main-is:          MyLibTest.hs
    build-depends:    base
