cabal-version:      3.0
name:               hons
version:            0.1.0.0
synopsis:           SCons-like build tool
homepage:           loonylinuxbox.mooo.com
license:            LGPL-3.0-or-later
license-file:       LICENSE
author:             Sergey Popov
maintainer:         loonycyborg@gmail.com
category:           Development

library
    exposed-modules:  Hons, Node, Rule, DepGraph, Taskmaster, Environment
    build-depends:    base
                    , filepath >= 1.5.0.0
                    , directory
                    , template-haskell
                    , algebraic-graphs >= 0.7
                    , containers
                    , unordered-containers
                    , text-short
                    , transformers
                    , hashable
                    , tagged
    hs-source-dirs:   src
    default-language: Haskell2010

executable hons
    main-is:          Main.hs
    build-depends:
        base,
        hons,
        filepath >= 1.5.0.0,
        algebraic-graphs >= 0.7,
        transformers

    hs-source-dirs:   app
    default-language: Haskell2010

test-suite hons-test
    default-language: Haskell2010
    type:             exitcode-stdio-1.0
    hs-source-dirs:   test
    main-is:          MyLibTest.hs
    build-depends:    base ^>=4.16.4.0
