on: [push]
name: build
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['9.10', '9.12']
        os: [ubuntu-latest, macOS-latest]
    name: GHC ${{ matrix.ghc }} on ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Haskell
        uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
      - name: Generate Freeze File
        run: cabal freeze
      - name: Cache Cabal Dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cabal/store
            dist-newstyle
          key: ${{ runner.os }}-cabal-${{ hashFiles('cabal.project.freeze') }}
          restore-keys: |
            ${{ runner.os }}-cabal-

      - name: Cabal Dependencies
        run: cabal build --only-dependencies --enable-tests
      - name: Build and Test
        run: |
          cabal run hons
          cabal test
